#!/usr/bin/python

import sys

class Node:
	def __init__(self, name):
		self.name = name
		self.sats = []
                self.body = None
                self.depth = 0
	def add_sat(self, sat):
		self.sats.append(sat)
                sat.body = self
                sat.depth = self.depth + 1

class OrbitMap:
	def __init__(self):
		self.nodes = { 'COM': Node('COM') }
	def add_sat(self, body, sat):
		if body not in self.nodes:
			raise KeyError("unknown body '{}'".format(body))
		if sat in self.nodes:
			raise RuntimeError("adding sat '{}' I already know about??".format(sat))
		self.nodes[sat] = Node(sat)
		self.nodes[body].add_sat(self.nodes[sat])

uom = OrbitMap()
queue = []

lines = open(sys.argv[1]).read().strip().split('\n')
queue = map(lambda line: line.split(')'), lines)

requeue = []

while queue:
    for body, sat in queue:
        try:
            uom.add_sat(body, sat)
        except KeyError:
            requeue.append((body, sat))
    queue = requeue
    requeue = []

def count_total_orbits(the_map):
    def count(node):
        return node.depth + sum(map(count, node.sats))
    return count(the_map.nodes['COM'])

print(count_total_orbits(uom))

def calc_xfer_dist(src, dst):
    path = []
    node = src
    while node is not None:
        path.append(node.name)
        node = node.body
    node = dst
    while node.name not in path:
        node = node.body

    return src.depth - node.depth + dst.depth - node.depth

if 'YOU' in uom.nodes and 'SAN' in uom.nodes:
    print(calc_xfer_dist(uom.nodes['YOU'].body, uom.nodes['SAN'].body))
