#!/usr/bin/python3

def fuel_needed(mass):
    total_needed = 0
    prev = mass
    while prev > 0:
        needed = prev // 3 - 2
        if needed > 0:
            total_needed += needed
        prev = needed
    return total_needed

assert fuel_needed(14) == 2
assert fuel_needed(1969) == 966
assert fuel_needed(100756) == 50346

total = 0
for line in open('input').readlines():
    n = int(line)
    total += fuel_needed(n)

print(total)
