#!/usr/bin/python3

import sys
import intcode

program = intcode.load_pgm('input')

def give(val):
    return lambda: val

buff = []
def fn_out(val):
    global buff
    buff.append(val)

intcode.run_pgm(program, give(1), fn_out)

for i in range(len(buff) - 1):
    assert buff[i] == 0

diagnostic_code = buff[-1]
print(diagnostic_code)

intcode.run_pgm(program, give(5), fn_out)

diagnostic_code = buff[-1]
print(diagnostic_code)
