#!/usr/bin/python

import sys
import intcode

program = intcode.load_pgm('input')

def fn_in():
    return 1

buff = []
def fn_out(val):
    global buff
    buff.append(val)

intcode.run_pgm(program, fn_in, fn_out)

for i in xrange(len(buff) - 1):
    assert buff[i] == 0

diagnostic_code = buff[-1]
print(diagnostic_code)
